name:                realworld-haskell
version:             0.1.0.0
github:              "githubuser/realworld-haskell"
license:             BSD3
author:              "pcz"
maintainer:          "example@example.com"
copyright:           "2017 pcz"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/realworld-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs:
    - contents
    - exercises
    - modules/ch5

executables:
  realworld-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - realworld-haskell

tests:
  realworld-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - realworld-haskell
